In [2]:
import cv2
import tensorflow as tf 
from tensorflow.keras.models import load_model
import numpy as np


In [5]:
pip install pygame


Note: you may need to restart the kernel to use updated packages.


In [3]:
from pygame import mixer


pygame 2.6.0 (SDL 2.28.4, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [4]:
face_cascade=cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model  = load_model('model//')

In [9]:


# Initialize face and eye cascade classifiers
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=3)

    for (x, y, w, h) in faces:
        # Draw rectangle around face
        cv2.rectangle(frame, pt1=(x, y), pt2=(x+w, y+h), color=(255, 0, 0), thickness=3)

        # Extract region of interest (ROI) for eyes within the face
        roi_gray = gray[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, scaleFactor=1.2, minNeighbors=3)
        
        for (ex, ey, ew, eh) in eyes:
            # Draw rectangle around eyes
            cv2.rectangle(frame, pt1=(x+ex, y+ey), pt2=(x+ex+ew, y+ey+eh), color=(0, 255, 0), thickness=3)
            
            # Preprocessing steps for eye detection
            eye = frame[y+ey:y+ey+eh, x+ex:x+ex+ew]
            eye = cv2.resize(eye, (80, 80))
            eye = eye / 255.0
            eye = eye.reshape(80, 80, 3)
            eye = np.expand_dims(eye, axis=0)
            
            # Prediction
            prediction = model.predict(eye)
            print(prediction)

            # Assuming the model output is a binary classification where:
            # 0 -> Eye Open
            # 1 -> Eye Closed
            if prediction[0][0] > 0.5:  # Assuming threshold for 'closed' is 0.5
                # Display "CLOSE" on the screen
                cv2.putText(frame, 'CLOSE', (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2, cv2.LINE_AA)
            else:
                # Display "OPEN" on the screen
                cv2.putText(frame, 'OPEN', (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2, cv2.LINE_AA)

    # Display the resulting frame
    cv2.imshow('frame', frame)
    
    # Exit the loop if 'q' is pressed
    if cv2.waitKey(33) & 0xFF == ord('q'):
        break

# Release the capture and close windows
cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 0s 144ms/step
[[0.48504746 0.5149525 ]]
1/1 [==============================] - 0s 125ms/step
[[0.31732088 0.6826791 ]]
1/1 [==============================] - 0s 67ms/step
[[0.1971545 0.8028455]]
1/1 [==============================] - 0s 63ms/step
[[0.26135 0.73865]]
1/1 [==============================] - 0s 66ms/step
[[0.05025741 0.94974256]]
1/1 [==============================] - 0s 62ms/step
[[0.00337921 0.9966208 ]]
1/1 [==============================] - 0s 62ms/step
[[0.01613322 0.9838668 ]]
1/1 [==============================] - 0s 61ms/step
[[0.00257916 0.9974208 ]]
1/1 [==============================] - 0s 59ms/step
[[9.0890750e-04 9.9909115e-01]]
1/1 [==============================] - 0s 64ms/step
[[0.24655354 0.75344646]]
1/1 [==============================] - 0s 65ms/step
[[0.7386404 0.2613596]]
1/1 [==============================] - 0s 61ms/step
[[0.6234219 0.3765781]]
1/1 [==============================] - 0s 64ms/step
[[0.34621492 0.6

1/1 [==============================] - 0s 68ms/step
[[0.7311425  0.26885748]]
1/1 [==============================] - 0s 64ms/step
[[0.08683185 0.91316813]]
1/1 [==============================] - 0s 63ms/step
[[0.08792584 0.9120742 ]]
1/1 [==============================] - 0s 66ms/step
[[0.02857643 0.97142357]]
1/1 [==============================] - 0s 64ms/step
[[0.3070122  0.69298786]]
1/1 [==============================] - 0s 71ms/step
[[0.1794715  0.82052845]]
1/1 [==============================] - 0s 70ms/step
[[8.583296e-04 9.991417e-01]]
1/1 [==============================] - 0s 63ms/step
[[0.02857999 0.97142   ]]
1/1 [==============================] - 0s 71ms/step
[[0.08571965 0.91428035]]
1/1 [==============================] - 0s 68ms/step
[[0.30127218 0.69872785]]
1/1 [==============================] - 0s 69ms/step
[[0.2227734  0.77722657]]
1/1 [==============================] - 0s 68ms/step
[[0.47844374 0.5215562 ]]
1/1 [==============================] - 0s 63ms/step
[[0.5550

1/1 [==============================] - 0s 75ms/step
[[0.17083386 0.8291662 ]]
1/1 [==============================] - 0s 64ms/step
[[0.00309264 0.9969074 ]]
1/1 [==============================] - 0s 62ms/step
[[0.00798948 0.9920106 ]]
1/1 [==============================] - 0s 71ms/step
[[0.11365293 0.8863471 ]]
1/1 [==============================] - 0s 70ms/step
[[0.20533256 0.7946674 ]]
1/1 [==============================] - 0s 66ms/step
[[0.0262364 0.9737636]]
1/1 [==============================] - 0s 66ms/step
[[0.00704881 0.9929512 ]]
1/1 [==============================] - 0s 72ms/step
[[0.01242409 0.9875759 ]]
1/1 [==============================] - 0s 68ms/step
[[0.06553979 0.93446016]]
1/1 [==============================] - 0s 70ms/step
[[0.0691998 0.9308002]]
1/1 [==============================] - 0s 70ms/step
[[0.17075656 0.8292434 ]]
1/1 [==============================] - 0s 66ms/step
[[0.01413291 0.9858671 ]]
1/1 [==============================] - 0s 64ms/step
[[0.10926149 0.8